# Generated by Django 2.1.1 on 2018-10-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ama', '0002_auto_20181026_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentprocesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=10)),
                ('pbrand', models.CharField(max_length=20)),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customeradd', models.CharField(max_length=500)),
            ],
        ),
    ]
