# Generated by Django 2.1.1 on 2018-10-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ama', '0005_auto_20181029_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprocesses',
            name='pprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
