# Generated by Django 2.1.1 on 2018-10-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ama', '0006_auto_20181029_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprocesses',
            name='pprice',
            field=models.IntegerField(default=5),
        ),
    ]
