# Generated by Django 2.1.1 on 2018-10-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ama', '0008_auto_20181029_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentprocesses',
            old_name='pprice',
            new_name='Money',
        ),
        migrations.RenameField(
            model_name='paymentprocesses',
            old_name='pname',
            new_name='cardname',
        ),
        migrations.RemoveField(
            model_name='paymentprocesses',
            name='pbrand',
        ),
        migrations.AddField(
            model_name='paymentprocesses',
            name='bankname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentprocesses',
            name='cardnumber',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='paymentprocesses',
            name='cardtype',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentprocesses',
            name='cvvno',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='paymentprocesses',
            name='watchesname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentprocesses',
            name='watchestypes',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
