# Generated by Django 2.1.1 on 2018-10-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ama', '0012_auto_20181030_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprocesses',
            name='cardtype',
            field=models.CharField(max_length=50),
        ),
    ]
